version: '3.8'
services:
  gateway:
    image: gateway
    build: gateway
    container_name: shareit-gateway
    network_mode: host
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHEREIT_SERVER_URL=http:/server:9090

  server:
    build: server
    image: server
    container_name: shareit-server
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
    depends_on:
      - postgresql

  postgresql:
    image: postgresql
    container_name: postgresql
    ports:
      - 6541:5432